### ISSUE TITLE
大佬，请问那个识别图片边缘那里用的是什么算法呀

### ISSUE THREAD

**Issue by KnowSky404** [tomhaoye/geetest-crack-demo#2]
那个识别图片边缘那里我看着好像是Canny边缘检测算法，想问一下是不是
最近老师让我们了解一下这个算法，没有实例，不是特别懂

**Comment by tomhaoye** [comment]
@LittleControl 
我的边缘检测只是一个比较简陋的检测规则，直接是通过颜色变化梯度进行检测的，而你说的算法它有比较完善的一套体系，具体可以看看维基百科，实际代码我也找了一篇文章，你可以参考一下：https://www.cnblogs.com/love6tao/p/5152020.html

**Comment by KnowSky404** [comment]
@tomhaoye 
好的好的，十分感谢
